Feature/cloud 1738 skip sonar analysis
variant-inc/actions-collection pull request #28
Opened 2022-06-01 15:36 UTC by naveen-variant

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes [#8](https://usxtech.atlassian.net/browse/CLOUD-8)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

```text
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
```

- [ ] Sanity Testing

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added documentation to test

2022-06-03 19:42 UTC, salyateem13 approved these changes

2022-06-06 19:53 UTC, jahnavimaddi approved these changes

2022-06-06 22:03 UTC, genghis-tuan requested changes
The result being placed in $CommitSha seem to be an entire object instead of just the SHA. I added a suggestion inline.

2022-06-07 19:31 UTC, genghis-tuan commented on scripts/skip_sonar_run.ps1
> +    }  | Select-Object -First 1 -ExpandProperty commit
Cleared this with Naveen. I did not go past the fetch.

2022-06-07 19:31 UTC, genghis-tuan approved these changes

2022-06-08 15:43 UTC, merged